import os
import random
import logging
from datetime import datetime, timedelta, timezone
from PIL import Image
from modules.config_loader import LOGO_FILE, QR_CODE_FILE, BG_DIR

logger = logging.getLogger(__name__)

def resize_by_width(img, target_width):
    original_width, original_height = img.size
    ratio = target_width / original_width
    target_height = int(original_height * ratio)

    resized_img = img.resize((target_width, target_height), Image.Resampling.LANCZOS)
    return resized_img


def compose_images(images, timezone_offset=9, bg_filter=None):
    """Compose images, optional blurred background and footer with HTML/CSS.

    Input images remain caller-owned. None selects white; [] selects a random
    built-in background; a list or configuration dict selects allowed files.
    """
    from modules.html_renderer import file_uri, image_uri, render_template
    images = list(images)
    if not images:
        raise ValueError("图片列表不能为空")
    inner_width = max(image.width for image in images)
    factor = inner_width / 1700
    font_size = max(24, min(40, int(28 * factor)))
    logo_size = max(100, min(180, int(130 * factor)))
    footer_height = max(max(150, min(250, int(150 * factor))), 30 + int(10 * factor) + logo_size)
    content_height = sum(image.height for image in images) + 5 * (len(images) - 1)
    width = inner_width + 80
    height = content_height + 5 + footer_height + 80
    entries = []
    y = 50
    for image in images:
        entries.append(dict(src=image_uri(image), x=40 + (inner_width-image.width)//2,
                            y=y, width=image.width, height=image.height))
        y += image.height + 5
    selected = bg_filter
    blur, overlay = 20, 40
    if isinstance(bg_filter, dict):
        selected = bg_filter.get('files', [])
        try:
            blur = max(0, min(40, int(bg_filter.get('blur', 20))))
        except (TypeError, ValueError):
            pass
        try:
            overlay = max(0, min(120, int(bg_filter.get('overlay', 40))))
        except (TypeError, ValueError):
            pass
    background = ''
    if selected is not None:
        try:
            files = [name for name in os.listdir(BG_DIR) if name.lower().endswith(('.png','.jpg','.jpeg','.webp'))]
            candidates = [name for name in selected if name in files] if selected else [name for name in files if not name.startswith('jietnguser_')]
            if candidates:
                background = file_uri(os.path.join(BG_DIR, random.choice(candidates)))
        except (OSError, TypeError, ValueError) as exc:
            logger.warning('[ImageManager] Background unavailable: %s', exc)
    now = datetime.now(timezone(timedelta(hours=timezone_offset)))
    sign = '+' if timezone_offset >= 0 else ''
    texts = [f"Generated by JiETNG at {now:%Y-%m-%d} (UTC{sign}{timezone_offset}).",
             f"© 2025 - {now.year} Matsuki (Matsuk1).", 'All rights reserved.']
    left = 40 + max(40, min(80, int(50 * factor))) - 10
    right = max(150, min(250, int(180 * factor))) - 10
    logo_x = 40 + inner_width - right
    qr_x = logo_x - logo_size - int(20 * factor)
    footer_y = 40 + content_height + 25
    with render_template('composition.html', width, height, entries=entries, background=background,
                         blur=blur, overlay=overlay/255, texts=texts, left=left,
                         text_width=max(1, qr_x-left-20), text_y=footer_y+int(20*factor),
                         font_size=font_size, line_spacing=max(30,min(50,int(35*factor))),
                         logo=file_uri(LOGO_FILE), qr=file_uri(QR_CODE_FILE),
                         logo_size=logo_size, logo_x=logo_x, qr_x=qr_x,
                         logo_y=footer_y+int(10*factor)) as rendered:
        return rendered.convert('RGB')


def compose_generated_images(images, **options):
    """Compose owned source images and release them when composition finishes."""
    images = list(images)
    try:
        options.pop("outer_margin", None)
        options.pop("image_y_offset", None)
        return compose_images(images, **options)
    finally:
        closed = set()
        for image in images:
            if id(image) not in closed:
                image.close()
                closed.add(id(image))

